=== asierblaz/LaVinoteca/contacto/librodevisitas/libro_visitas.dtd
<!ELEMENT visitas (visita)*>
<!ATTLIST visitas ult_id IDREF #REQUIRED>
<!ELEMENT visita (fecha, nombre, comentario, email?)>
<!ATTLIST visita id ID #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email mostrar (si|no) "no">

=== asierblaz/LaVinoteca/contacto/librodevisitas/data/libro_visitas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE visitas SYSTEM "libro_visitas.dtd">
<visitas ult_id="visita10"><visita id="visita1"><fecha>Mon, 07 Dec 2015 16:29:10 +0100</fecha><nombre>Asier</nombre><comentario>He estado muy a gusto en la vinoteca.</comentario></visita><visita id="visita2"><fecha>Mon, 07 Dec 2015 16:59:20 +0100</fecha><nombre>Gonzalo</nombre><comentario>Buen trato</comentario></visita><visita id="visita3"><fecha>Mon, 07 Dec 2015 17:00:16 +0100</fecha><nombre>Gonzalo</nombre><comentario>Buen trato</comentario></visita><visita id="visita4"><fecha>Mon, 07 Dec 2015 17:02:24 +0100</fecha><nombre>Gonzalo</nombre><comentario>Buen trato</comentario></visita><visita id="visita5"><fecha>Mon, 07 Dec 2015 17:03:08 +0100</fecha><nombre>Gonzalo</nombre><comentario>Buen trato</comentario></visita><visita id="visita6"><fecha>Mon, 07 Dec 2015 17:22:17 +0100</fecha><nombre>Mari Jose</nombre><comentario>Trato personal.</comentario></visita><visita id="visita7"><fecha>Mon, 07 Dec 2015 18:10:05 +0100</fecha><nombre>Paco</nombre><comentario>Hola</comentario></visita><visita id="visita8"><fecha>Tue, 08 Dec 2015 11:59:04 +0100</fecha><nombre>Pepe</nombre><comentario>Muy bien</comentario></visita><visita id="visita9"><fecha>Tue, 08 Dec 2015 11:59:21 +0100</fecha><nombre>Pepe</nombre><comentario>super bien!</comentario></visita><visita id="visita10"><fecha>Tue, 08 Dec 2015 12:28:27 +0100</fecha><nombre>Manolo</nombre><comentario>Los vinos son caros</comentario><email mostrar="si">manolo@gmail.com</email></visita></visitas>
